apiVersion: batch/v1
kind: Job
metadata:
  name: db-job
#  namespace: default
spec:
  completions: 1
  parallelism: 1
  # Время жизни Job после завершения (в секундах)
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: db-job
    spec:
      restartPolicy: Never
      containers:
        - name: db-container
          image: mantogin/mantogin-crud-user-db:1.0.0
          command: ["/bin/sh"]
#          args: ["-c", "echo 'Hello from Kubernetes Job!' && sleep 10 && echo 'Job completed successfully'"]
#          args: ["-c", "echo '$(PG_PASSWORD)' $(PG_IP) '$(DB_PASSWORD)' $(DB_USER)"]
          args: ["-c", "PGPASSWORD='$(PG_PASSWORD)' psql -h $(PG_IP) -p 5432 -U postgres -f /db/drop_db.sql -f /db/create_db.sql && PGPASSWORD='$(DB_PASSWORD)' psql -h $(PG_IP) -p 5432 -U $(DB_USER) -d mcua_db -f /db/create_table.sql"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PG_IP
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: pgIp
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: pg_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_password
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config-map