{
 "title": "hw5",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency (response time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri, method, instance))",
     "legendFormat": "0.5 quantile {{instance}} {{method}}:{{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri, method, instance))",
     "legendFormat": "0.95 quantile {{instance}} {{method}}:{{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])) by (le, uri, method, instance))",
     "legendFormat": "0.99 quantile {{instance}} {{method}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Latency (response time) from nginx-ingress-controller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/mantogin-crud-user-app.*\"}[1m])) by (le, method, instance))",
     "legendFormat": "0.5 quantile {{instance}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/mantogin-crud-user-app.*\"}[1m])) by (le, method, instance))",
     "legendFormat": "0.95 quantile {{instance}} {{method}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/mantogin-crud-user-app.*\"}[1m])) by (le, method, instance))",
     "legendFormat": "0.99 quantile {{instance}} {{method}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (instance, method, uri) (rate(http_server_requests_seconds_count{uri=~\"/user.*\"}[1m]))",
     "legendFormat": "{{instance}} {{method}}:{{uri}}"
    }
   ]
  },
  {
   "title": "RPS from nginx-ingress-controller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (instance, method) (rate(nginx_ingress_controller_requests{path=~\"/mantogin-crud-user-app.*\"}[1m]))",
     "legendFormat": "{{instance}} {{method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance, method, uri) (rate(http_server_requests_seconds_count{uri=~\"/user.*\", status=\"500\"}[1m]))",
     "legendFormat": "{{instance}} {{method}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate  from nginx-ingress-controller",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance, method, uri) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/mantogin-crud-user-app.*\", status=\"500\"}[1m]))",
     "legendFormat": "{{instance}} {{method}}"
    }
   ]
  }
 ]
}